extensions:
  - PhpSpec\Extension\CodeCoverageExtension

code_coverage:
  format:
    - clover
    - html
  output:
    html: build/logs/coverage
    clover: build/logs/clover.xml

suites:
    main:
        namespace: Happyr\DoctrineSpecification
        psr4_prefix: Happyr
        specPath: spec
