language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - ./run-phpspec.sh

after_success:
  - php vendor/bin/coveralls -v

