language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - composer require --no-update satooshi/php-coveralls:~0.6@stable
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - ./run-phpspec.sh

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

